// <auto-generated />
using System;
using ChessWebsite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Website_for_Chess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251230133536_addadminloginandregistration")]
    partial class addadminloginandregistration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChessWebsite.Models.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentId"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EntryFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FifthPlacePrize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FirstPlacePrize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FourthPlacePrize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrganizerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PrizePool")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RegistrationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("SecondPlacePrize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThirdPlacePrize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TimeControl")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("TournamentId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Tournaments");

                    b.HasData(
                        new
                        {
                            TournamentId = 1,
                            ContactEmail = "championship@chessfed.org",
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2025, 12, 30, 21, 35, 35, 776, DateTimeKind.Local).AddTicks(7618),
                            CurrentParticipants = 45,
                            Description = "Annual championship for elite chess players with substantial prize pool",
                            EndDate = new DateTime(2026, 1, 31, 21, 35, 35, 776, DateTimeKind.Local).AddTicks(7626),
                            EntryFee = 500.00m,
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 12, 30, 21, 35, 35, 776, DateTimeKind.Local).AddTicks(7619),
                            Location = "International Convention Center",
                            MaxParticipants = 100,
                            Name = "Grand Chess Championship 2024",
                            OrganizerName = "Chess Federation International",
                            PrizePool = 50000.00m,
                            RegistrationDeadline = new DateTime(2026, 1, 24, 21, 35, 35, 776, DateTimeKind.Local).AddTicks(7634),
                            Rules = "FIDE rules apply. Minimum rating: 2000. Dress code: Formal.",
                            StartDate = new DateTime(2026, 1, 29, 21, 35, 35, 776, DateTimeKind.Local).AddTicks(7621),
                            Status = 1,
                            TimeControl = "120+30",
                            Type = 5
                        },
                        new
                        {
                            TournamentId = 2,
                            ContactEmail = "events@citychessclub.com",
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2025, 12, 30, 21, 35, 35, 776, DateTimeKind.Local).AddTicks(7639),
                            CurrentParticipants = 32,
                            Description = "Fast-paced blitz tournament for speed chess enthusiasts",
                            EndDate = new DateTime(2026, 1, 6, 21, 35, 35, 776, DateTimeKind.Local).AddTicks(7641),
                            EntryFee = 25.00m,
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 12, 30, 21, 35, 35, 776, DateTimeKind.Local).AddTicks(7640),
                            Location = "City Chess Club",
                            MaxParticipants = 50,
                            Name = "Blitz Battle Royale",
                            OrganizerName = "City Chess Club",
                            PrizePool = 1000.00m,
                            RegistrationDeadline = new DateTime(2026, 1, 4, 21, 35, 35, 776, DateTimeKind.Local).AddTicks(7644),
                            Rules = "Blitz rules. No delay. Double elimination format.",
                            StartDate = new DateTime(2026, 1, 6, 21, 35, 35, 776, DateTimeKind.Local).AddTicks(7641),
                            Status = 1,
                            TimeControl = "3+2",
                            Type = 3
                        },
                        new
                        {
                            TournamentId = 3,
                            ContactEmail = "tournaments@chessmasters.com",
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2025, 12, 30, 21, 35, 35, 776, DateTimeKind.Local).AddTicks(7645),
                            CurrentParticipants = 178,
                            Description = "Weekly online rapid chess tournament open to all players",
                            EndDate = new DateTime(2026, 1, 2, 21, 35, 35, 776, DateTimeKind.Local).AddTicks(7647),
                            EntryFee = 10.00m,
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 12, 30, 21, 35, 35, 776, DateTimeKind.Local).AddTicks(7646),
                            Location = "Online - ChessMasters Platform",
                            MaxParticipants = 200,
                            Name = "Online Rapid Arena",
                            OrganizerName = "ChessMasters",
                            PrizePool = 2000.00m,
                            RegistrationDeadline = new DateTime(2026, 1, 1, 21, 35, 35, 776, DateTimeKind.Local).AddTicks(7649),
                            Rules = "Platform rules apply. Fair play monitored. No takebacks.",
                            StartDate = new DateTime(2026, 1, 2, 21, 35, 35, 776, DateTimeKind.Local).AddTicks(7646),
                            Status = 0,
                            TimeControl = "15+10",
                            Type = 6
                        });
                });

            modelBuilder.Entity("ChessWebsite.Models.TournamentRegistration", b =>
                {
                    b.Property<int>("TournamentRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentRegistrationId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("TournamentRegistrationId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentRegistrations");
                });

            modelBuilder.Entity("ChessWebsite.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 12, 30, 21, 35, 35, 776, DateTimeKind.Local).AddTicks(7444),
                            Email = "admin@chessmasters.com",
                            IsActive = true,
                            IsAdmin = true,
                            LastLogin = new DateTime(2025, 12, 30, 21, 35, 35, 776, DateTimeKind.Local).AddTicks(7447),
                            PasswordHash = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ChessWebsite.Models.Tournament", b =>
                {
                    b.HasOne("ChessWebsite.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("ChessWebsite.Models.TournamentRegistration", b =>
                {
                    b.HasOne("ChessWebsite.Models.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });
#pragma warning restore 612, 618
        }
    }
}
